ENV['host'] = 'localhost'
ENV['db_name'] = 'mocknequi'
ENV['user_name'] = 'root'
ENV['password'] = ''
ENV['socket'] = 'D:/Programs/Xampp/mysql/mysql.sock'
ENV['port'] = '3306'
ENV['mysql_executable'] = 'D:/Programs/Xampp/mysql'
